config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root 'articles#index'
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }
  resources :articles 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, length: { maximum: 30 }

  has_many :articles, dependent: :destroy
  after_commit :user_welcome, on: :create

  enum gender: {
    male: 0,
    female: 1,
    other: 3
  }

  def user_welcome
    UserWelcomeJob.perform_later(id)
  end

  private

  def set_defaults
    self.gender ||= :other
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token

  def authenticate
    return redirect_to new_user_session_path, notice: 'Please login to access.' unless user_signed_in?
    
    authenticate_or_request_with_http_basic do |email, password|
      user = User.find_by(email: email)
      !user.nil? && user.valid_password?(password)
    end
    warden.custom_failure! if performed?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :authenticate
  before_action :authenticate_user!
  before_action :set_user
  before_action :verify_user, only: %i[show edit destroy]

  def index
    @articles = current_user.articles
    respond_to do |format|
      format.html
      format.json { render json: current_user.articles, status: 200 }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @article.to_json, status: 200 }
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article.to_json, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    @article = Article.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render json: @article.to_json, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { render json: "Deleted Successfully", status: :ok }
    end
  end

  private

  def set_user
    @current_user = current_user
  end

  def verify_user
    @article = Article.find_by(id: params[:id])
    if @article.try(:user_id) != current_user.id
      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'You are not authorized' } 
        format.json { render json: "You are not authorized", status: :ok } 
      end
    end
  end

  def article_params
    params.require(:article).permit(:user_id, :title, :body, :image)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = Galafarms3Schema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :update_allowed_parameters, only: %i[update]
  respond_to :json

  # GET /resource/sign_up (/users/sign_up)
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    respond_to do |format|
      if resource.save
        format.html { redirect_to '/', notice: 'User is successfully created.' }
        format.json { render json: resource, status: 200 }
      else
        format.html { render :new }
        format.json { render json: resource.errors, status: :unprocessable_entity }
      end
     end 
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super do |user|
      respond_to do |format|
        if user.errors.present?
          format.html { return render :new , notice: user.errors}
          format.json { return render json: user.errors, status: :unprocessable_entity }
        else
          format.html 
          format.json { return render json: user, status: 200 }
        end
      end
    end
  end

  # DELETE /resource
  def destroy
    current_user.destroy
    render json: "User Account Deleted Successfully", status: :ok
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:first_name, :last_name, :gender, :address, :phone, :password, :current_password)
    end
  end

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :gender, :email, :password)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < Devise::SessionsController
   
  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
  
end
  
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <%= form_with model: @article do |form| %>
    <%= render 'shared/errors', object: article %>

    <%= form.hidden_field :user_id, value: @current_user.id %>
    
    <div class="form-group">
      <%= form.label :title %><br>
      <%= form.text_field :title, class: "form-control form-control-lg", placeholder: "Title" %>
    </div>

    <div class="form-group">  
      <%= form.label :body %><br>
      <%= form.text_area :body, class: "form-control",rows: "5", placeholder: "Enter Content..." %>
    </div>

    <div class="custom-file">
      <%= form.label :image, class: "custom-file-label" %><br>
      <%= form.file_field :image, class: "custom-file-input" %>
    </div>

    <hr/>

    <div>
      <%= form.submit %>
    </div>
    
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="card">
  <center>
    <%= image_tag "banner.jpg", class:"d-block image-banner" %>
    <%= image_tag "banner-2.jpg", class:"d-block image-banner" %>
    <%= image_tag "banner-3.jpg", class:"d-block image-banner" %>
  </center>
</div>

<section class="text-center dark">
  <h4 class="mb-5" style="color:white"><strong>Articles</strong></h4>
  <div class="container">
    <div class="row"> 
      <% @articles.each do |article| %>
        <div class="col-lg-4 col-md-6 m-4">
          <div class="card">
            <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
              <div class="img-overlay">
                <%= link_to '<button style="background-color: black; border: none; opacity: 0.6; color: white; cursor:pointer ">Read More</button>'.html_safe , article %>
              </div>
            </div>
            <div class="card-body">
              <h5 class="card-title">
                <%= article.title %>
              </h5>
              <p class="card-text">
                <%= article.body %>
              </p>
              <a href="#" class="btn btn-outline-primary btn-sm">
                Card link
              </a>
              <a href="#" class="btn btn-outline-secondary btn-sm">
                <i class="far fa-heart"></i>
              </a>
            </div>
          </div>
        </div>
      <% end %>    
    </div>
  </div>
</section>
  
  


 

app/views/articles/new.html.erb
<div class="text-center padding"><h2>Add Article</h2></div>  
<%= render 'form' , article: @article %>

app/views/articles/show.html.erb
 <section class="dark">
  <div class="container py-4">
    <h1 class="h1 text-center" id="pageHeaderTitle"><%= @article.title %></h1>
    <article class="postcard dark blue">
      <div class="postcard__text">
        <h1 class="postcard__title blue"><a href="#"><%= @article.title %></a></h1>
        <div class="postcard__subtitle small">
          <time datetime="2020-05-25 12:00:00">
            <i class="fas fa-calendar-alt mr-2"></i><%= @article.created_at %>
          </time>
        </div>
        <div class="postcard__bar"></div>
        <div class="postcard__preview-txt h3"><%= @article.body %></div><br />
        <%= image_tag(@article.image_url, style: "border: 2px solid gray; width: 50%; height: 50%; margin: 10px") if @article.image? %>
        <ul class="postcard__tagbox">
          <li class="tag__item h3"> <i class="fas fa-edit"></i><%= link_to "Edit", edit_article_path(@article), class:"btn btn-primary", style: "margin: 10px" %></li>
          <li class="tag__item h3"><i class="fas fa-trash"></i><%= link_to "Destroy", article_path(@article), class:"btn btn-primary", style: "margin: 10px",
              method: :delete,
              data: { confirm: "Are you sure?" } %>
          </li>
        </ul>
      </div>
    </article>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Galafarms3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <%= render "shared/menu" %>
  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <footer class="footer mt-auto py-3 bg-light card-footer">
      <div class="container">
        <span class="text-muted">© 2021 Copyright: Galafarms</span>
      </div>
    </footer>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <h3>Some Errors were found </h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li> <%= message %> </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/" id="home">Home</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="/articles"  id="mposts">My Blogs</a>
          </li>
        <% end %>
      </ul>
      <div class="d-flex">
        <% if !user_signed_in? %>
          <%= link_to "Login", "/users/sign_in", class:"btn btn-outline-dark", style: "margin-right: 10px" %>
          <%= link_to "Signup", "/users/sign_up", class:"btn btn-outline-dark", style: "margin-right: 10px" %>
        <% else %>
          <%= link_to 'Create Blog', new_article_path, class:"btn btn-outline-dark", style: "margin-right: 10px" %>
          <%= link_to 'Edit Profile', "/users/edit", class:"btn btn-outline-dark", style: "margin-right: 10px" %>
          <%= link_to "Logout", destroy_user_session_path, :method => :delete, class:"btn btn-outline-danger", style: "margin-right: 10px" %>
        <%end %>
      </div>
    </div>
  </div>
</nav>